### ISSUE TITLE
Self hosted

### ISSUE THREAD

**Issue by kubeworkz** [TheNileDev/examples#134]
Can Nile be entirely self-hosted in a dev lab? Like, is the admin dashboard open source and self-hostable? Cheers, Dave

**Comment by ybyzek** [comment]
@kubeworkz no, not at this time.  If you want to share more about the use case, please reach out via the form on https://www.thenile.dev, we'd love to to hear about it.

**Comment by kubeworkz** [comment]
Thanks.
